FROM python:3.10.9

# Update the software
RUN apt-get update
RUN apt-get upgrade -y

# Get the Mask R-CNN repository.
RUN git clone --branch docker-object-detection https://github.com/briannaosms/parking-occupancy-detection-system.git

# Set the working directory of the container
WORKDIR /parking-occupancy-detection-system/object-detection/Mask-RCNN-TF2/

# Install the prerequisite software.
RUN pip3 install -r requirements.txt && \
    python setup.py install

# Download pretrained COCO weights.
RUN wget https://github.com/matterport/Mask_RCNN/releases/download/v2.0/mask_rcnn_coco.h5

# Install COCO API.
RUN wget https://github.com/waleedka/coco/archive/refs/heads/master.zip -O coco.zip && \
    unzip coco.zip && \
    rm coco.zip && \
    cd coco-master/PythonAPI && \
    make

# copy files
COPY images/ /object-detection/images/

# Run 
CMD [ "bash" ]

# Debug
# CMD [ "bash" ]