# Generated by Django 4.1.5 on 2023-02-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Parkinglots",
            fields=[
                ("lot_name", models.CharField(max_length=255)),
                (
                    "spaceID",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("type", models.CharField(max_length=255)),
                ("availability", models.SmallIntegerField()),
            ],
        ),
    ]
